- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
- mico-grapheditor/src/mico-graph.ts
- mico-grapheditor/src/object-cache.ts
- mico-grapheditor/src/templates.ts
- mico-grapheditor/test.html
Node-Templates are now only stored in object cache. The `type` attribute in node datum is used to determine which template to use. The id 'default' can overwrite the standard default template.
> Add multi template support based on node.type

- mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceControllerTests.java
---
Getting correct external IP of Kubernetes service.
IP of load balancer ingress is required, not the external IP of the service itself.
Resolves #336
> Fix getting correct external IP

- mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java
- mico-core/src/main/java/io/github/ust/mico/core/util/CollectionUtils.java
- mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
- mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java
---
Fixes creation of redundant creation of Kubernetes objects for same MicoServices (Kubernetes Deployments) and MicoServiceInterfaces (Kubernetes Services).
Resolves #405
> Fix redundant creation of Kubernetes objects

- mico-core/src/main/java/io/github/ust/mico/core/exception/KubernetesResourceException.java
- mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
- mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java
- mico-core/src/main/java/io/github/ust/mico/core/web/ServiceInterfaceController.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceControllerTests.java
---
Refactor implementation of getting Kubernetes objects for deployed MicoServices and MicoServiceInterfaces.
`MicoKubernetesClient` offers following methods to be able to get the Kubernetes objects of deployed MicoServices and MicoServiceInterfaces:
* `getDeploymentOfMicoService`
* `getInterfacesOfMicoService`
* `getInterfaceByNameOfMicoService`
Furthermore the method `isApplicationDeployed` offers the possibility to check if a MicoApplication is already deployed.
Resolves #408
Resolves #409
Resolves #410
> Refactor getting of deployed MICO services and interfaces

- mico-admin/package-lock.json
- mico-admin/package.json
- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
- mico-admin/src/app/graphs/graphs.module.ts
As the grapheditor is now published on npm the dependency needs to be updated.
Closes #191
> Update grapheditor dependency to point to published npm package

- mico-core/src/main/java/io/github/ust/mico/core/dto/KubernetesNodeMetricsDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/MicoServiceStatusDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/service/MicoStatusService.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoStatusServiceTest.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java
- mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java
---
For an improved handling in the frontend, the separated maps for average CPU and memory values per node in a MicoServiceStatusDTO are replaced with a list of KubernetesNodeMetricsDTOs.
Resolves #523
> Refactor MicoServiceStatusDTO to use KubernetesNodeMetricsDTO

- mico-core/src/main/java/io/github/ust/mico/core/util/Patterns.java
---
Fixes wrong regex for validation of Semantic Versioning.
Bug was introduced with #455
> Fix Regex for validation of Semantic Versioning

- mico-core/pom.xml
Updates two dependencies:
* fabric8 Kuberentes: 4.1.2 → 4.1.3
* Spring Cloud Starter Kubernetes Config: 1.0.0 → 1.0.1
> Bump fabric8 Kubernetes to version 4.1.3

- mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoApplicationRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceInterfaceRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/util/KubernetesNameNormalizer.java
- mico-core/src/test/java/io/github/ust/mico/core/KubernetesNameNormalizerTests.java
---
Sets the new max size for shortNames to ~~63~~. A limit of 54 is necessary because a UID is generated and concatenated with the shortName to form a label.
Closes #560
> Fix max size limit of shortNames

- mico-core/src/main/java/io/github/ust/mico/core/service/imagebuilder/ImageBuilder.java
- mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderTests.java
---
Fixes naming of Kubernetes Builds using also the version of a *MicoService*.
Resolves #586
> Fix naming of Kubernetes Build now using service version

- mico-core/src/main/java/io/github/ust/mico/core/service/MicoStatusService.java
---
If no replica of a deployment is available in Kubernetes (e.g. a pod crashed and can not be restarted), MicoStatusService produced a NullPointerException when requesting the available replicas. This issue is fixed by a short check, if there are more available replicas than unavailabe ones.
Fixes #598
> Fix NP if no replicas are available

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
Update of a service deployment information does not remove relation to the corresponding MICO service anymore.
Resolves #667.
> Fix update of service deployment information

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
Endpoint must return an empty list if there are no applications instead of throwing an error
> Fix get application by short name

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceInterfaceBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java
Endpoint should return an empty list if there are no MICO services with the particular short name instead of returning an error status code.
> Fix get all versions of a MICO service

- install/kubernetes/test-setup-all-in-own-namespace.sh
Fix test script `install/kubernetes/test-setup-all-in-own-namespace.sh`. Knative Build and Prometheus were not deployed in the specified namespace.
> Fix test script for deploying all in own namespace

- mico-core/src/main/java/io/github/ust/mico/core/broker/DeploymentBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoService.java
- mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
- mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceIntegrationTests.java
If the property 'kafkaEnabled' of an *MicoService* is set to `true`, no service interface is required during deployment.
Closes #744
> Add new MicoService property 'kafkaEnabled'

- mico-core/src/main/java/io/github/ust/mico/core/util/PrometheusValueDeserializer.java
- mico-core/src/test/java/io/github/ust/mico/core/PrometheusValueDeserializerTest.java
This PR does not change any behavior. It only prevents that no NPE is logged when Prometheus returns no result.
Closes #764
> Fixed NPE when Prometheus returns no value

- docker-compose.yml
- install/kubernetes/neo4j.yaml
Bump Neo4j to version 3.5.8 (before 3.5.3).
Changelog: https://neo4j.com/release-notes/
Tested locally.
> Bump Neo4j to version 3.5.8

- pom.xml
Bump Spring Boot to version 2.1.7 (before 2.1.6).
Changelog: https://github.com/spring-projects/spring-boot/releases/tag/v2.1.7.RELEASE
> Bump Spring Boot to version 2.1.7

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/configuration/KafkaConfig.java
- mico-core/src/main/java/io/github/ust/mico/core/configuration/OpenFaaSConfig.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceDeploymentInfoRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoTopicRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceDeploymentInfoResponseDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoTopicResponseDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/exception/MicoTopicRoleNotUniqueException.java
- mico-core/src/main/java/io/github/ust/mico/core/exception/MicoTopicRoleUsedMultipleTimesException.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoEnvironmentVariable.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoTopic.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoTopicRole.java
- mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoTopicRepository.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
- mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
- mico-core/src/main/java/io/github/ust/mico/core/util/Patterns.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceIntegrationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/DefaultEnvironmentVariablesConfigurationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoRepositoryTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoServiceDeploymentInfoRepositoryTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoTopicRepositoryTests.java
- mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java
- mico-core/src/test/java/io/github/ust/mico/core/util/MicoRepositoryTestUtils.java
> Add `MicoTopic` as a property of `MicoServiceDeploymentInfo` to MICO

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceDeploymentInfoBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceDeploymentInfoResource.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceIntegrationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceDeploymentInfoIntegrationTests.java
Refactoring: Create own classes for entity `MicoServiceDeploymentInfo`:
- `ServiceDeploymentInfoResource`
- `MicoServiceDeploymentInfoBroker`
- `ServiceDeploymentInfoIntegrationTests`
Contains fix for Neo4j to finally saving all topics like expected. Basically the workaround is to delete all relationships to the existing topics of the particular `MicoServiceDeploymentInfo` node and recreate them. Works fine :)
Relates to #761 
Closes #784
> Refactor MicoServiceDeploymentInfo and fix Neo4j bug

- mico-admin/package-lock.json
- mico-admin/package.json
- mico-admin/src/app/app.module.ts
- mico-admin/src/app/dialogs/graph-add-kafka-topic/graph-add-kafka-topic.component.html
- mico-admin/src/app/dialogs/graph-add-kafka-topic/graph-add-kafka-topic.component.spec.ts
- mico-admin/src/app/dialogs/graph-add-kafka-topic/graph-add-kafka-topic.component.ts
- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph-constants.ts
- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
Add topics to application grapheditor. Only input and output topics will be shown to avoid clutter.
#780
> Add topics to app dependency graph

- docs/mico-core/java/io/github/ust/mico/core/dto/response/KFConnectorDeploymentInfoResponseDTO.rst
- mico-core/src/main/java/io/github/ust/mico/core/dto/response/KFConnectorDeploymentInfoResponseDTO.java
Add Kubernetes deployment info to response DTO of the KafkaFaasConnector.
Closes #800.
> Add Kubernetes deployment info to reponse DTO

- docs/mico-core/java/io/github/ust/mico/core/broker/MicoServiceDeploymentInfoBroker.rst
- docs/mico-core/java/io/github/ust/mico/core/persistence/MicoServiceDeploymentInfoRepository.rst
- mico-core/src/main/java/io/github/ust/mico/core/broker/DeploymentBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceDeploymentInfoBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoServiceDeploymentInfoRepository.java
- mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceIntegrationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoServiceDeploymentInfoRepositoryTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceDeploymentInfoIntegrationTests.java
Because of the changes introduced with #790 it's now possible that there are multiple service deployment information for the same service short name and version within an application.
Therefore the find methods in the repository have to be modified, so that a list is returned instead of an `Optional`.
- x ] Ensure that new source files include the [license header](https://github.com/UST-MICO/mico/blob/master/CONTRIBUTING.md#source-file-headers)
> Fix find methods for getting service deployment information

- docs/mico-core/java/io/github/ust/mico/core/broker/MicoApplicationBroker.rst
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
- mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java
Refactor and improve implementation of deleting KafkaFaasConnector instances from an application.
Add tests.
Relates to #793
> Refactor endpoints to delete KafkaFaasConnector instances

- mico-core/src/main/java/io/github/ust/mico/core/broker/KafkaFaasConnectorDeploymentInfoBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/DeploymentResource.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/KafkaFaasConnectorDeploymentInfoResource.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceDeploymentInfoResource.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceIntegrationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceIntegrationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java
- mico-core/src/test/java/io/github/ust/mico/core/KafkaFaasConnectorDeploymentInfoResourceEndToEndTests.java
- mico-core/src/test/java/io/github/ust/mico/core/ServiceDeploymentInfoIntegrationTests.java
Adds the following endpoints:
- GET `/applications/<short-name>/<version>/kafkaFaasConnectorDeploymentInformation/`
Relates to #750
Relates to #798
> Add endpoints for KafkaFaasConnector deployment information

- mico-core/src/main/java/io/github/ust/mico/core/dto/response/KFConnectorDeploymentInfoResponseDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationWithServicesResponseDTO.java
Add KafkaFaasConnector service information to the application response DTO.
> Adds the KafkaFaasConnector service information to the application dto

- mico-core/src/main/java/io/github/ust/mico/core/dto/request/KFConnectorDeploymentInfoRequestDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoEnvironmentVariable.java
Add OpenFaaSFunctionName to environment variables
closes #797
> Add OpenFaaSFunctionName to env vars

- mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoServiceDeploymentInfoRepository.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
If a service was deleted from an application it also deletes all related properties like topics.
However if a topic is also used by another service deployment information it must not be deleted from the database.
This PR fixes this problem by only deleting related properties if they are used exclusively by the particular service deployment information.
> Fix Neo4j queries to delete only exclusively used properties

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceDeploymentInfoResponseDTO.java
- mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceInstanceNotFoundException.java
- mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceNotFoundException.java
- mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
Part of #743 _Multiple Instance Deployment_.
Also makes the implementation of #817 (part of epic #750) easier because an `instanceId` is required to be able to deploy and undeploy specific instances of *MicoServices*.
This PR covers not _Multiple Instance Deployment_ as a whole, it only introduces the `instanceId` to all *MicoServiceDeploymentInfo* entities to ensure, that it is always given.
-> Multiple Instances of a normal *MicoService* are not supported! Only multiple instances of a KafkaFaasConnector will be supported with the final implementation of the epic #750.
There should be a possible to reuse existing MicoService instances.
Therefore this PR adds an optional `instanceId` to the API endpoint method `addServiceToApplication`:
`POST …
> Add optional parameter instanceId to be able to reuse existing instances

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
change kfconnectorversion from request parameter to query parameter
closes #811
> change kfconnectorversion from request parameter to query parameter

- mico-core/src/main/java/io/github/ust/mico/core/broker/KafkaFaasConnectorDeploymentInfoBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceDeploymentInfoBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/dto/request/KFConnectorDeploymentInfoRequestDTO.java
- mico-core/src/test/java/io/github/ust/mico/core/KafkaFaasConnectorDeploymentInfoResourceEndToEndTests.java
PUT endpoint for updating KafkaFaasConnector instances don't require following properties anymore:
- `inputTopicName`
- `outputTopicName`
- `openFaaSFunctionName`
> Fix PUT endpoint so that properties are not required anymore

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
Apply default deployment information when a new KafkaFaaSConnector instance is added
closes #831
> Apply default deployment information when a kfconn new instance is added

- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph-constants.ts
- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
Show if kafka faas connector is ready for deployment directly in the grapheditor.
(input topic and one of output topic or faas function have to be set)
> Add validity checks for kf connectors in grapheditor

- mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/KafkaFaasConnectorDeploymentInfoResource.java
Adds the missing self links to POST kfconnectorDeploymentInfo
Closes #837
> Add missing self-links to POST kfconnectorDeploymentInfo

- mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
Fix some errors shown in console when cancelling a dialog in the grapheditor.
> Fix ui errors on dialog cancel in grapheditor

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceDeploymentInfoBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/configuration/KafkaConfig.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
- mico-core/src/test/java/io/github/ust/mico/core/DefaultEnvironmentVariablesConfigurationTests.java
The group id has to be unique for every logical deployment unit.
The instanceId already has this property.
Closes #847
> Fix kafka group id semantic

- mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
Add OpenFaaS function name as EnvVar to Kubernetes deployment.
> Fix missing OpenFaaS function name as EnvVar during deployment

- install/kubernetes/mico-core.yaml
- mico-core/src/main/java/io/github/ust/mico/core/configuration/OpenFaaSConfig.java
- mico-core/src/main/java/io/github/ust/mico/core/resource/OpenFaasResource.java
- mico-core/src/main/resources/application-dev.properties
- mico-core/src/main/resources/application-local.properties
- mico-core/src/main/resources/application-prod.properties
- mico-core/src/main/resources/application-unit-testing.properties
- mico-core/src/test/java/io/github/ust/mico/core/DefaultEnvironmentVariablesConfigurationTests.java
- mico-core/src/test/java/io/github/ust/mico/core/OpenFaasResourceTests.java
Use two different configuration properties for OpenFaaS gateway URI, to be able to test `mico-core` and `kafka-faas-connector` locally.
Closes #786
> Add two different config properties for OpenFaaS gateway URI

- install/kubernetes/kafka/kafka/test/produce-consume.yml
- install/kubernetes/kafka/zookeeper/50pzoo.yml
- install/kubernetes/kafka/zookeeper/51zoo.yml
Increases memory limits of ZooKeeper used by Kafka.
Closes #860
> Increase memory limits of ZooKeeper for Kafka

- docker-compose.yml
- install/kubernetes/neo4j.yaml
Neo4j version 3.5.8 → 3.5.11:
- [Release notes 3.5.11](https://neo4j.com/release-notes/neo4j-3-5-11/)
- [Release notes 3.5.9](https://neo4j.com/release-notes/neo4j-3-5-9/)
> Bump Neo4j to version 3.5.11

- pom.xml
Spring Boot version 2.1.7 → 2.1.8 ([release notes](https://github.com/spring-projects/spring-boot/releases/tag/v2.1.8.RELEASE))
Most relevant: Upgrade of Neo4j Ogm 3.1.13
> Bump Spring Boot to version 2.1.8

- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
- mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceDeploymentInfoBroker.java
- mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceEndToEndTests.java
Related nodes of a `MicoServiceDeploymentInformation` entity were not deleted if the entity itself was deleted. This PR removes all tangling nodes after a normal MicoService or a KafkaFaasConnector is removed from a application.
> Fix deleting tangling service deployment information

- mico-core/src/main/java/io/github/ust/mico/core/service/MicoStatusService.java
- mico-core/src/test/java/io/github/ust/mico/core/MicoStatusServiceTest.java
Inside the status DTO of a service the deployment status of the using applications was not set.
```json
{
"shortName": "test-message-generator",
"version": "v1.1.0",
"name": "UST-MICO/test_message_generator",
"instanceId": "test-message-generator-yf6fyflj",
"requestedReplicas": 1,
"availableReplicas": 1,
"interfacesInformation": [],
"applicationsUsingThisService": [
{
"shortName": "kafka-faas-deployment",
"version": "v0.0.1",
"name": "kafka-faas-deployment-application",
"description": "Real World application with a frontend and a backend",
"contact": null,
"owner": null,
"deploymentStatus": {
"value": "Deployed",
"messages": [
{
"content": "The MicoApplication is currently deployed.",
"type": "Info"
}
]
}
}
],
"podsInformation": [
{
"podName": …
```
> Fix deployment status of application within status service dto

- mico-admin/src/app/app-detail-overview/app-detail-overview.component.html
- mico-admin/src/app/app-detail-overview/app-detail-overview.component.ts
Add add kafka faas connector button to be able to add new connectors without dragging links from topics. This allows apps that only use topics and kafka faas connectors to be build in the UI.
> Add add kf connector button

- mico-admin/docker-entrypoint.sh
Rather than trying to operate on the nginx.conf file in place (see below on why this fails), this PR changes the docker entrypoint to create a temporary file and then replace nginx.conf with that one.
There are no breaking changes in this PR.
Currently, the mico-admin docker entrypoint reads and writes the nginx.conf in the same shell command. This is a race condition that often leads to erasing the contents of the nginx.conf, because
- the file is opened for reading (fine)
- the file is opened for writing *and truncated* so it's empty
- then envsubst tries to do its job, but ends up doing nothing because the file it's trying to read is empty
The shellcheck wiki has an article about this class of problems: https://github.com/koalaman/shellcheck/wiki/SC2094
- (not applicable: no new files) …
> mico-admin entrypoint: avoid truncating nginx.conf
