mico-admin/Dockerfile
mico-admin/nginx.conf
mico-admin/pom.xml
mico-core/Dockerfile
mico-core/pom.xml
pom.xml

---
Add functionality to automatically build a docker image with every Maven build.
#38, #47

Add docker build automation for mico-core and mico-admin.

---

mico-core/src/main/java/io/github/ust/mico/core/DependsOn.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceRepository.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java

---
This commit adds a test for storing an application with its dependencies to the database.
Fixes issue #27 .

Add test for storing an application

---

mico-admin/pom.xml

---
Adds the --force option to the linter.

Add --force flag to nom runt lint.

---

mico-core/pom.xml
mico-core/src/main/java/io/github/ust/mico/core/ClusterAwareness.java
mico-core/src/test/java/io/github/ust/mico/core/ClusterAwarenessTest.java

---
base functions to get informations from kubernetes cluster
[Issue 77](https://github.com/UST-MICO/mico/issues/77)

base cluster awareness

---

mico-core/src/main/java/io/github/ust/mico/core/Service.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceInterface.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceInterfaceRepository.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java
mico-core/src/test/java/io/github/ust/mico/core/SpringDataRestTests.java

---
Renaming ServiceDescription to ServiceInterface and ServiceDescriptionRepository to ServiceInterfaceRepository.
Fixes issue #91 .

Renaming ServiceDescription to ServiceInterface

---

mico-core/src/main/java/io/github/ust/mico/core/ServiceInterface.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java
mico-core/src/test/java/io/github/ust/mico/core/SpringDataRestTests.java

---
Refactoring methods and attributs to match smallCamelCase.
Fixes issue #92 .

Refactoring methods and attributes to match smallCamelCase

---

mico-core/src/main/java/io/github/ust/mico/core/Application.java
mico-core/src/main/java/io/github/ust/mico/core/ApplicationRepository.java
mico-core/src/main/java/io/github/ust/mico/core/DependsOn.java
mico-core/src/main/java/io/github/ust/mico/core/DependsOnRepository.java
mico-core/src/main/java/io/github/ust/mico/core/Service.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceInterfaceRepository.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceRepository.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java
mico-core/src/test/java/io/github/ust/mico/core/SpringDataRestTests.java

Implementing some previous TODOs

---

mico-admin/src/app/api/models.service.ts
mico-admin/src/app/forms/mico-form-boolean/mico-form-boolean.component.html
mico-admin/src/app/forms/mico-form-number/mico-form-number.component.html
mico-admin/src/app/forms/mico-form-question/mico-form-question.component.html
mico-admin/src/app/forms/mico-form/mico-form.component.ts
mico-admin/src/app/service-detail-overview/service-detail-overview.component.html

Add startData attribute to form to prefill form.
Add title Attribute awareness (title is preferred over x-key attributes of properties in UI)
Sort properties by x-order in mico-form
Model merging not working (previously unused)

Add title attribute awareness and start data to mico-form

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/api/models.service.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/dialogs/create-service-interface/create-service-interface.component.html
mico-admin/src/app/dialogs/create-service-interface/create-service-interface.component.spec.ts
mico-admin/src/app/dialogs/create-service-interface/create-service-interface.component.ts
mico-admin/src/app/dialogs/yes-no-dialog/yes-no-dialog.component.html
mico-admin/src/app/dialogs/yes-no-dialog/yes-no-dialog.component.ts
mico-admin/src/app/service-detail-overview/service-detail-overview.component.css
mico-admin/src/app/service-detail-overview/service-detail-overview.component.html
mico-admin/src/app/service-detail-overview/service-detail-overview.component.ts

---
Displays the service interfaces in the service detail overview and offers Dialogs to create/delete service interfaces.
#63

Add create-service-interface component

---

README.md
mico-core/pom.xml
mico-core/src/main/java/io/github/ust/mico/core/ClusterAwareness.java
mico-core/src/main/java/io/github/ust/mico/core/ClusterAwarenessFabric8.java
mico-core/src/test/java/io/github/ust/mico/core/ClusterAwarenessFabric8Test.java
mico-core/src/test/java/io/github/ust/mico/core/ClusterAwarenessTest.java
mico-core/src/test/resources/hello-kubernetes-deployment.yaml
mico-core/src/test/resources/hello-kubernetes-w-namespace.yaml
mico-core/src/test/resources/hello-kubernetes.yaml

---
Using fabric8io for comminucation with the cluster
[Issue](https://github.com/UST-MICO/mico/issues/99)

implemented cluster awareness with fabric8io

---

mico-admin/src/app/dialogs/service-picker/service-picker.component.css
mico-admin/src/app/dialogs/service-picker/service-picker.component.html
mico-admin/src/app/dialogs/service-picker/service-picker.component.ts
mico-admin/src/app/service-detail-overview/service-detail-overview.component.ts

---
The service picker from #63 will be refactored to be more generic.

Generic Service Picker

---

mico-core/src/main/java/io/github/ust/mico/core/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceRepository.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java

---
The following methods for crawling from GitHub Repositories are supported:
* crawl latest release
* crawl specific release
* crawl all releases
Resolves #93 .
Resolves #94 .

GitHub Crawler Updates

---

mico-core/src/main/java/io/github/ust/mico/core/CrawlingSource.java
mico-core/src/main/java/io/github/ust/mico/core/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/Service.java
mico-core/src/main/java/io/github/ust/mico/core/VersionNotSupportedException.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java

Update Service class

---

mico-admin/src/app/app-detail-overview/app-detail-overview.component.html
mico-admin/src/app/app-detail-overview/app-detail-overview.component.ts
mico-admin/src/app/app-detail/app-detail.component.html
mico-admin/src/app/app-detail/app-detail.component.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.html
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.spec.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
mico-admin/src/app/graphs/graphs.module.ts
mico-admin/tslint.json
mico-grapheditor/src/mico-graph.ts

---
Adds angular components that use network-graph webcomponent.
Closes #134

angular graph components

---

mico-grapheditor/src/mico-graph.ts
mico-grapheditor/src/textwrap.ts
mico-grapheditor/test.html

Add basic text wrapping capabitlities to text tags in graph (based on width attribute and css text wrapping attributes)

text wrapping in graph

---

mico-core/src/main/java/io/github/ust/mico/core/ClusterAwarenessFabric8.java
mico-core/src/test/java/io/github/ust/mico/core/ClusterAwarenessFabric8Test.java

- [x ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x ] Ensure to use auto format in **all** files
- [x ] Tests created for change
---
Method signatures are now consistent
#157

Fix method signature inconsistencies

---

mico-core/pom.xml
pom.xml

---
Bump dependency versions to latest:
* Spring Boot to 2.1.1
* Kubernetes Client to 4.1.1

Update dependencies - Spring Boot and Kubernetes client

---

mico-core/src/main/java/io/github/ust/mico/core/MicoCoreApplication.java

---
Removed unnecessary REST endpoint
Closes issue #164

Remove REST endpoint "/test"

---

mico-core/pom.xml
mico-core/src/main/java/io/github/ust/mico/core/GitHubCrawler.java
mico-core/src/main/resources/application.properties
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java
mico-core/src/test/java/io/github/ust/mico/core/Neo4jTestClass.java

---
Resolves #107 .
Resolves #120 .

Make use of embedded Neo4j Database and SetUp & TearDown methods

---

mico-core/src/main/java/io/github/ust/mico/core/ApplicationRepository.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java

Creates application endpoints

---

docs/mico-core/tests/integration-tests.rst
mico-core/pom.xml
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderIntegrationTests.java

---
Jenkins can now run the integration tests on the connected Kubernetes cluster.

Execute integration tests with Jenkins

---

mico-core/pom.xml

---
Removed redundant dependency declaration of lombok.

Remove redundant lombok dependency

---

pom.xml

---
Update Spring Boot version from 2.1.1 to 2.1.2

Bump spring boot version to 2.1.2

---

mico-core/src/main/java/io/github/ust/mico/core/Service.java

---
Add the  @ApiModelProperty(required = true) to name in Service
#197

Add requiered annotation to service name

---

mico-core/src/main/java/io/github/ust/mico/core/Application.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java

Feature/mico205 PUT /applications/{shortName}/{version}

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/ServiceRepository.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java

Feature/mico200 implement DELETE /services/{shortName}/{version}

---

docs/mico-core/java/backgroud-task-architecture.rst
mico-core/src/main/java/io/github/ust/mico/core/MicoCoreApplication.java
mico-core/src/main/java/io/github/ust/mico/core/concurrency/MicoCoreBackgroundTaskDemo.java
mico-core/src/main/java/io/github/ust/mico/core/concurrency/MicoCoreBackgroundTaskFactory.java
mico-core/src/main/java/io/github/ust/mico/core/concurrency/MicoCoreBackgroundTaskFactoryConfig.java
mico-core/src/main/resources/application.properties
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreBackgroundTaskFactoryTests.java

---
Add mini framework for running tasks in the background with support for on-success and on-failure callbacks.
#95, #144

Background task mini-framework

---

mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/ImageBuilder.java
mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/buildtypes/BuildStatus.java
mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/buildtypes/ClusterSpec.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoService.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderTests.java

---
`ImageBuilder` uses now the new domain model as input.
Part of #97.

Refactor ImageBuilder to use new domain model

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDependency.java

---
Remove unused imports and unused fields.

Remove unused imports and unused fields.

---

mico-core/src/main/java/io/github/ust/mico/core/CustomOpenApiExtentionsPlugin.java
mico-core/src/main/java/io/github/ust/mico/core/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/NotInitializedException.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/VersionNotSupportedException.java
mico-core/src/main/java/io/github/ust/mico/core/WebConfig.java
mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/ImageBuilder.java

---
Remove unused imports, add generic type arguments where possible.

Remove unused imports, add generic type arguments where possible.

---

mico-core/src/main/java/io/github/ust/mico/core/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java

Add API Endpoint for GitHub Crawler

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplication.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoApplicationRepository.java

Fix Post /applications/
---
resolves #251

Add GET /applications/{shortName}

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplication.java

---
Adds a draft implementation POST /applications/{shortName}/{version}/services
#266

[WIP] Add draft implementation for adding services to applications

---

mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerIntegrationTests.java

---
Service now connects to the correct pod.
Part of #281

Fix service association to pod in cluster

---

mico-core/src/main/java/io/github/ust/mico/core/REST/DeploymentController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoImageContainer.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoService.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceControllerTests.java

---
Deployed services with a service interface should be accessible from the outside of the cluster.
REST API should provide the public IP.
Resolves #281

Feature/281 Provide public service IP

---

mico-core/src/main/java/io/github/ust/mico/core/DeploymentException.java
mico-core/src/main/java/io/github/ust/mico/core/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/ImageBuildException.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/WebConfig.java
mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/BuildList.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java

---
Check IDE warning, remove unused stuff, add generic type parameters, minor optimizations.

Clean up code, add generic type parameters, minor optimizations.

---

install/kubernetes/mico-core.yaml
mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/resources/application.properties

---
Add environment variables for Prometheus.
Resolves #300

Add Prometheus URI environment variable

---

Dockerfile.mico-admin

try make docker-entrypoint runnable under unix

make runnable

---

docker-compose.yml
install/kubernetes/neo4j.yaml

---
Set neo4j image to community version 3.5.2
Resolves #311

Fix explicit neo4j image version

---

Dockerfile.mico-admin
mico-admin/docker-entrypoint.sh
mico-admin/nginx.conf

add nameserver var

---

mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java

---
Fixes failing unit tests in ServiceControllerTests.
Resolves #329

Fix ServiceControllerTests

---

install/kubernetes/mico-admin.yaml

using FQDN like provided here https://stackoverflow.com/questions/40682677/dns-does-not-resolve-with-nginx-in-kubernetes

using FQDN

---

install/kubernetes/mico-core.yaml
mico-core/pom.xml
mico-core/src/main/resources/application.properties
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java

---
Embedded Neo4j is used instead of real database.
Neo4j configuration in Kubernetes cluster is applied via a ConfigMap.
Resolves #294

Fix Neo4j unit tests

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplication.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplicationDeploymentInfo.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoApplicationRepository.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoServiceRepository.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java

---
Get and create endpoints for applications (except applications with deployment information) and services working now.
Resolves #340.

Fix application and service endpoints including database queries.

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java

adds the missing delete endpoint `/applications/{shortName}/{version}`
closes #310

Add delete endpoint for applications

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceControllerTests.java

---
Fixes REST endpoint GET publicIP.
Resolves #336

Fix endpoint GET public IP

---

mico-core/src/main/java/io/github/ust/mico/core/CorsConfig.java
mico-core/src/main/java/io/github/ust/mico/core/WebConfig.java
mico-core/src/main/resources/application.properties
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceControllerTests.java

---
Add DELETE to allowed methods and allow further configuration via application.properties.
#351

[WIP] Fix/mico 351 cors delete

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java

Endpoint now loads all provided services from db before saving the application.
Closes #365

Fix posting a new application modifying included services

---

mico-core/src/main/java/io/github/ust/mico/core/REST/RequestLoggingFilterConfig.java
mico-core/src/main/resources/application.properties

---
Add logging for each request.
Closes #368

Add logging for each request

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java

---
Fix REST endpoints that enforced using a trailing slash.
Closes #370

Fix REST endpoints that enforced a trailing slash

---

mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java

---
Remove trailing slash to fix test in service controller tests (`getVersionsOfService()`).

Remove trailing slash to fix test in service controller tests.

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/DeploymentController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java

Response status exception

---

install/kubernetes/mico-admin.yaml
install/kubernetes/setup.sh

---
Setup script for MICO deployment is interactive now. Also, the public IP of the load balancer in mico-admin is optional.
#289

Public IP of MICO is optional now

---

mico-core/src/main/java/io/github/ust/mico/core/REST/DeploymentController.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/AmbiguousKubernetesResourceException.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/KubernetesResourceException.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java
mico-core/src/main/java/io/github/ust/mico/core/util/CollectionUtils.java
mico-core/src/main/java/io/github/ust/mico/core/util/UIDUtils.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerIntegrationTests.java

---
Apply correct labels to each created Kubernetes resource. Use unique identifiers for unambiguousness.
Resolves #298.

Implement naming strategy of Kubernetes resources (unique identifiers).

---

mico-core/src/main/java/io/github/ust/mico/core/REST/DeploymentController.java

---
Fix the Null pointer exception that was caused when no ServiceDeploymentInfo was provided for a MicoApplication.
Resolves #397

Fix NPE in MicoApplication property ServiceDeploymentInfo

---

mico-core/src/main/java/io/github/ust/mico/core/ClusterAwarenessFabric8.java
mico-core/src/main/java/io/github/ust/mico/core/CustomOpenApiExtentionsPlugin.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/DeploymentController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceController.java
mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/ImageBuilder.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java
mico-core/src/test/java/io/github/ust/mico/core/ClusterAwarenessFabric8Test.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderTests.java
mico-core/src/test/java/io/github/ust/mico/core/LombokFluentChainTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceControllerTests.java

---
* Apply IntelliJ Idea warnings
* Refactor HTTP NotFound and BadRequest exceptions to return error message and to be consistent
* Refactor Kubernetes API client
* Add Lombok unit tests for fluent chain accessors

Refactor controllers

---

mico-core/src/main/java/io/github/ust/mico/core/REST/DeploymentController.java
mico-core/src/main/java/io/github/ust/mico/core/imagebuilder/ImageBuilder.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerTests.java
mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java

---
Deployment don't throw an NullPointerException anymore if container ports are missing.
Depends on #282 
Resolves #345

[WIP] Fix/345 deployment npe

---

mico-core/src/main/java/io/github/ust/mico/core/REST/ServiceInterfaceController.java
mico-core/src/main/java/io/github/ust/mico/core/mapping/MicoKubernetesClient.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceControllerTests.java

---
Fix GET public IP of MICO service interface.
Add label `interface` to Kubernetes service to be able to get the Kubernetes service by this label.
Resolves #401

Fix get public IP of service interface

---

install/kubernetes/mico-core.yaml
mico-core/src/main/java/io/github/ust/mico/core/REST/ApplicationController.java

---
Fixes wrong Prometheus URI.
Resolves #323

Fix Prometheus URI

---

mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java

quick changes on assert to use correct variables
#246

Fix tests mico core

---

mico-core/src/main/java/io/github/ust/mico/core/dto/UiApplicationDeploymentInformation.java
mico-core/src/main/java/io/github/ust/mico/core/dto/UiServiceDeploymentInformation.java
mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTest.java

---
Fixes GET deployment information for a whole MICO application with multiple services.
Resolves #412

Fix GET deployment information for all services of an application

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/api/semantic-version.ts
mico-admin/src/app/app-detail/app-detail.component.html
mico-admin/src/app/app-detail/app-detail.component.ts
mico-admin/src/app/app-list/app-list.component.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/dialogs/create-next-version/create-next-version.component.html
mico-admin/src/app/dialogs/create-next-version/create-next-version.component.spec.ts
mico-admin/src/app/dialogs/create-next-version/create-next-version.component.ts
mico-admin/src/app/service-list/service-list.component.ts

Adds a button to the application view of the latest version to promote a new version, which inherits the specification from the latest version
#393

Add button to promote next application version

---

mico-core/src/main/java/io/github/ust/mico/core/service/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/web/ServiceController.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerIntegrationTests.java

Add Exception Handling for GitHub Crawler

---

mico-core/src/main/java/io/github/ust/mico/core/service/GitHubCrawler.java
mico-core/src/main/java/io/github/ust/mico/core/web/CrawlingInformation.java
mico-core/src/main/java/io/github/ust/mico/core/web/ServiceController.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java

[Backend] Update API Endpoints for GitHub Crawler

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/api/models.service.ts
mico-admin/src/app/app-detail-overview/app-detail-overview.component.html
mico-admin/src/app/app-detail-overview/app-detail-overview.component.ts
mico-admin/src/app/app-detail-status/app-detail-status.component.html
mico-admin/src/app/app-detail-status/app-detail-status.component.spec.ts
mico-admin/src/app/app-detail-status/app-detail-status.component.ts
mico-admin/src/app/app-detail/app-detail.component.html
mico-admin/src/app/app-detail/app-detail.component.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/data-view/mico-data-object/mico-data-object.component.html
mico-admin/src/app/dialogs/create-service-interface/create-service-interface.component.ts
mico-admin/src/app/service-detail-status/service-detail-status.component.html
mico-admin/src/app/service-detail-status/service-detail-status.component.spec.ts
mico-admin/src/app/service-detail-status/service-detail-status.component.ts
mico-admin/src/app/service-detail/service-detail.component.html
mico-admin/src/styles.css

Adds deploy information (status) of applications and services.
#148 (partly)

Add application/service deploy status

---

install/kubernetes/setup.sh
install/kubernetes/test-setup.sh

---
Update of the outdated test setup script .
Closes #470

Update test setup script

---

mico-core/src/main/java/io/github/ust/mico/core/dto/MicoServiceDeploymentInfoDTO.java

---
Add DTO for service deployment information.
Resolves #476.

Add DTO for service deployment information.

---

mico-core/src/main/java/io/github/ust/mico/core/web/DeploymentController.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/IntegrationTestsUtils.java

---
Fixes the integration tests regarding image building and deployment
Resolves #495

Fix deployment integration tests

---

mico-core/src/main/java/io/github/ust/mico/core/configuration/MicoKubernetesBuildBotConfig.java
mico-core/src/main/java/io/github/ust/mico/core/service/imagebuilder/ImageBuilder.java
mico-core/src/main/resources/application.properties

---
Increases build timeout from 1 minute to 10 minutes.
Resolves #474

Increase build timeout to 10 minutes

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/dashboard/dashboard.component.ts
mico-admin/src/app/dialogs/create-service/create-service.component.html
mico-admin/src/app/dialogs/create-service/create-service.component.ts

Allows to import the latest or a specific version of a future mico service via github.
#462

Feature/mico 462 ui for GitHub import

---

mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java

---
Fixes delete of all versions of specific MicoApplication instead of deleting all applications in the database.
Resolves #498

Fix delete all versions of an application

---

mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplication.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoService.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDependency.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceInterface.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServicePort.java

Make id's read-only

---

mico-admin/src/app/api/apimodel.ts
mico-admin/src/app/forms/mico-form-question/mico-form-question.component.html
mico-admin/src/app/forms/mico-form-question/mico-form-question.component.ts

Adds form input for enums.
Closes #486

Add form element for enums

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/dialogs/update-service-interface/update-service-interface.component.html
mico-admin/src/app/dialogs/update-service-interface/update-service-interface.component.spec.ts
mico-admin/src/app/dialogs/update-service-interface/update-service-interface.component.ts
mico-admin/src/app/service-detail-overview/service-detail-overview.component.css
mico-admin/src/app/service-detail-overview/service-detail-overview.component.html
mico-admin/src/app/service-detail-overview/service-detail-overview.component.ts

Add dialog and api function to update service interfaces.
Closes #487

Add ui to update service interfaces

---

mico-core/pom.xml
mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
mico-core/src/test/java/io/github/ust/mico/core/MicoStatusServiceTest.java
pom.xml

---
Updated dependencies:
* Spring Boot: 2.1.2 → 2.1.3 (includes Lombok version update 1.18.4 → 1.18.6)
* fabric8 Kubernetes Client: 4.1.1 → 4.1.2

Update versions of Spring Boot and Kubernetes client

---

Jenkinsfile

Jenkins pipeline now contains a when clause in every step so the step is executed only when there is a change on master.

Update Jenkinsfile to trigger stages only if there is a change on master

---

mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java

---
Refactor endpoint to add services to have no request body but corresponding path variables instead.
#529.

Refactor endpoint to add services to an application.

---

mico-core/src/test/java/io/github/ust/mico/core/ApplicationControllerTests.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentControllerTests.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java

---
Refactor test constants so that all constants required for integration tests are encapsulated in the `TestConstants` class.

Refactor test constants

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/app-detail-overview-deployment-information/app-detail-overview-deployment-information.component.html
mico-admin/src/app/app-detail-overview-deployment-information/app-detail-overview-deployment-information.component.spec.ts
mico-admin/src/app/app-detail-overview-deployment-information/app-detail-overview-deployment-information.component.ts
mico-admin/src/app/app-detail-overview/app-detail-overview.component.html
mico-admin/src/app/app-detail-overview/app-detail-overview.component.ts
mico-admin/src/app/app-detail-status/app-detail-status.component.html
mico-admin/src/app/app-detail-status/app-detail-status.component.ts
mico-admin/src/app/app-detail/app-detail.component.html
mico-admin/src/app/app-list/app-list.component.html
mico-admin/src/app/app-list/app-list.component.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/dashboard/dashboard.component.ts
mico-admin/src/app/data-view/mico-data-array/mico-data-array.component.html
mico-admin/src/app/dialogs/create-application/create-application.component.html
mico-admin/src/app/dialogs/create-application/create-application.component.ts
mico-admin/src/app/dialogs/deployment-information-dialog/deployment-information-dialog.component.html
mico-admin/src/app/dialogs/deployment-information-dialog/deployment-information-dialog.component.spec.ts
mico-admin/src/app/dialogs/deployment-information-dialog/deployment-information-dialog.component.ts
mico-admin/src/app/forms/mico-form-object/mico-form-object.component.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
mico-admin/src/app/service-detail-status/service-detail-status.component.html
mico-admin/src/app/service-detail-status/service-detail-status.component.ts

Shows deployment Information at the application overview page and offers a dialogue to modify it.
Improves array-handling for empty arrays in mico-data-view
Updates api connection for (application|service)/status
#478

Feature/mico 478 ui to set/modify deployment information

---

Jenkinsfile

Jenkins didn't build anything due to conditionals that leads to that every stage was skipped. The conditional where introduced with #516.
We have to remove the conditionals again.

Fix Jenkinsfile remove when condition

---

mico-admin/package-lock.json
mico-admin/package.json
mico-admin/src/app/api/api.service.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
mico-admin/src/app/graphs/graphs.module.ts
mico-admin/src/app/graphs/service-dependency-graph/graph-constants.ts
mico-admin/src/app/graphs/service-dependency-graph/service-dependency-graph.component.html
mico-admin/src/app/graphs/service-dependency-graph/service-dependency-graph.component.spec.ts
mico-admin/src/app/graphs/service-dependency-graph/service-dependency-graph.component.ts
mico-admin/src/app/service-detail/service-detail.component.html

Dependency graph for services using the new endpoint.

Add service dependency graph

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/app-detail-overview/app-detail-overview.component.ts
mico-admin/src/app/app-detail/app-detail.component.ts
mico-admin/src/app/app-list/app-list.component.css
mico-admin/src/app/app-list/app-list.component.html
mico-admin/src/app/app-list/app-list.component.ts
mico-admin/src/app/dialogs/deployment-information-dialog/deployment-information-dialog.component.html
mico-admin/src/app/forms/mico-form-array/mico-form-array.component.html
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts
mico-admin/src/app/service-list/service-list.component.css
mico-admin/src/app/service-list/service-list.component.html
mico-admin/src/app/service-list/service-list.component.ts
mico-admin/src/styles.css

Adds additional 'add (Application|Service)' buttons in the corresponding list views.
Improves the service list
Improves the formatting of the description inside the application/service list
Update the POST applicationService endpoint connection
#480

[WIP] Feature/mico ui optimization for easier usage

---

Jenkinsfile

Slack notification is outsourced to a new method which is executed in the post section.

Update Jenkinsfile to fix Slack notifications

---

mico-admin/nginx.conf

---
Fixes Nginx configuration. Query parameters are now forwarded correctly.
Resolves #558.

Fix Nginx configuration

---

mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationJobStatusResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceBackgroundTaskResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/resource/BackgroundTaskResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/DeploymentResource.java

---
Move `MicoApplicationJobStatusResponseDTO` and `MicoServiceBackgroundTaskResponseDTO` to the DTO response package.

Move job DTOs to correct package.

---

mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoServiceRepository.java

---
Fix parameter naming in query in `MicoServiceRepository`.

Fix query in service repository.

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/app-detail/app-detail.component.ts

Use the promote application endpoint in the UI to create a new application version.
Closes #566

Add promoteApplication to api service

---

mico-core/src/main/java/io/github/ust/mico/core/MicoCoreApplication.java
mico-core/src/main/java/io/github/ust/mico/core/broker/BackgroundTaskBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/DeploymentResource.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java

Refactor background task broker

---

mico-core/src/main/java/io/github/ust/mico/core/broker/BackgroundJobBroker.java
mico-core/src/main/java/io/github/ust/mico/core/configuration/MicoCoreBackgroundJobFactoryConfig.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationJobStatusResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceBackgroundJobResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplicationJobStatus.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceBackgroundJob.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoBackgroundJobRepository.java
mico-core/src/main/java/io/github/ust/mico/core/resource/BackgroundJobResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/DeploymentResource.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoCoreBackgroundJobFactory.java
mico-core/src/test/java/io/github/ust/mico/core/BackgroundJobResourceTest.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreBackgroundJobFactoryTests.java

---
rename from task to job to be consistent with endpoint
#580

change use of task to job

---

mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceTests.java

return 404 on not found service for their status
resolves #573

return not found on endpoint instead of body

---

mico-core/src/main/java/io/github/ust/mico/core/persistence/KubernetesDeploymentInfoRepository.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoEnvironmentVariableRepository.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoLabelRepository.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoServiceInterfaceRepository.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceInterfaceResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceResourceTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceIntegrationTests.java

---
Fix `GET` endpoints for `MicoServiceInterfaces`
- `GET /services/{shortName}/{version}/interfaces getInterfacesOfService`
- `GET /services/{shortName}/{version}/interfaces/{serviceInterfaceName} getInterfaceByName`
by using correct repository and query.
Add custom query to `MicoServiceInterfaceRepository` to get all `MicoServiceInterfaces` of a particular `MicoService`.
Fixes #585.

Fix/mico#585 Get Interfaces of Service

---

mico-core/src/main/java/io/github/ust/mico/core/exception/DeploymentException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/GlobalExceptionHandler.java
mico-core/src/main/java/io/github/ust/mico/core/exception/ImageBuildException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoApplicationAlreadyExistsException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoApplicationDoesNotIncludeMicoServiceException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoApplicationIsDeployedException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoApplicationNotFoundException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceAlreadyAddedToMicoApplicationException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceAlreadyExistsException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceDeploymentInformationNotFoundException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceHasDependersException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceInterfaceAlreadyExistsException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceIsDeployedException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceNotFoundException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/NotInitializedException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/PrometheusRequestFailedException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/ShortNameOfMicoApplicationDoesNotMatchException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/VersionNotSupportedException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/VersionOfMicoApplicationDoesNotMatchException.java

Preparation for #537 | Add Exceptions

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceBroker.java
mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceInterfaceBroker.java

Preparation for #537 | Rename Broker Files

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceBroker.java
mico-core/src/main/java/io/github/ust/mico/core/broker/ServiceBroker.java
mico-core/src/test/java/io/github/ust/mico/core/MicoServiceBrokerTests.java

Add MicoServiceBroker and associated tests

---

mico-core/src/main/java/io/github/ust/mico/core/resource/DeploymentResource.java

Hopefully fixes the sporadic failure of the unit test `DeploymentResourceTests.deployApplicationWithOneServiceAndOneServiceInterface`.
Log:
```
[ERROR] Failures: 
[ERROR]   DeploymentResourceTests.deployApplicationWithOneServiceAndOneServiceInterface:180 
micoServiceRepository bean.save(
<Capturing argument>
);
Wanted 1 time:
-> at io.github.ust.mico.core.DeploymentResourceTests.deployApplicationWithOneServiceAndOneServiceInterface(DeploymentResourceTests.java:180)
But was 0 times.
```

Fix sporadic failed tests with Jenkins

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceEndToEndTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceUnitTests.java

Update ServiceResource | Part of #537

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceAddedMoreThanOnceToMicoApplicationException.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceIntegrationTests.java

Add Application Broker for #537

---

Dockerfile.mico-core.integrationtests
Dockerfile.mico-core.unittests
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceIntegrationTests.java

Fix Jenkins build.
Resolves #623

Fix Jenkins build

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceInterfaceBroker.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceInterfaceNotFoundException.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceInterfaceResource.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceResourceIntegrationTests.java

Update ServiceInterfaceResource + Broker | Issue #537

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java
mico-core/src/test/java/io/github/ust/mico/core/MicoServiceBrokerTests.java

Add check for already existing application / service when promoting application / service

---

mico-core/src/main/java/io/github/ust/mico/core/broker/DeploymentBroker.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoApplicationDoesNotIncludeMicoServiceException.java
mico-core/src/main/java/io/github/ust/mico/core/exception/MicoServiceInterfaceNotFoundException.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/DeploymentResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java
mico-core/src/test/java/io/github/ust/mico/core/ApplicationResourceIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/BackgroundJobResourceTest.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/GitHubCrawlerTests.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ImageBuilderTests.java
mico-core/src/test/java/io/github/ust/mico/core/IntegrationTestsUtils.java
mico-core/src/test/java/io/github/ust/mico/core/JsonPathBuilder.java
mico-core/src/test/java/io/github/ust/mico/core/KubernetesNameNormalizerTests.java
mico-core/src/test/java/io/github/ust/mico/core/LombokFluentChainTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoServiceBrokerTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoStatusServiceTest.java
mico-core/src/test/java/io/github/ust/mico/core/MicoVersionTests.java
mico-core/src/test/java/io/github/ust/mico/core/PrometheusValueDeserializerTest.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceInterfaceResourceIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceEndToEndTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceIntegrationTests.java
mico-core/src/test/java/io/github/ust/mico/core/ServiceResourceUnitTests.java
mico-core/src/test/java/io/github/ust/mico/core/SwaggerTests.java
mico-core/src/test/java/io/github/ust/mico/core/TestConstants.java

Implement DeploymentBroker | Issue #537

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java

Fix GET /{applications}

---

mico-admin/src/app/api/apimodel.ts
mico-admin/src/app/api/models.service.ts
mico-admin/src/app/forms/mico-form-array/mico-form-array.component.html
mico-admin/src/app/forms/mico-form-array/mico-form-array.component.ts
mico-admin/src/app/forms/mico-form-object/mico-form-object.component.ts

Updates the model service of he ui for better/easier dynamic forms/data views
The title of arrays is now shown correctly in dynamic forms.

Update the model service, Fix dynamic forms array title

---

mico-core/src/main/java/io/github/ust/mico/core/broker/DeploymentBroker.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
mico-core/src/main/resources/application.properties
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java

---
Fixes scale in functionality of the undeployment of *MicoApplications*.
Resolves #638.

Fix scale in while undeployment of a MicoApplication

---

mico-core/src/main/java/io/github/ust/mico/core/dto/response/KubernetesDeploymentInfoResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationJobStatusResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationWithServicesResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceBackgroundJobResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceDependencyGraphEdgeResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceDependencyGraphResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceDeploymentInfoResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceInterfaceResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoYamlResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/ValidationErrorResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/status/KubernetesNodeMetricsResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/status/KubernetesPodInformationResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/status/KubernetesPodMetricsResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/status/MicoApplicationStatusResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/status/MicoServiceInterfaceStatusResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/status/MicoServiceStatusResponseDTO.java

---
Removed the `@JsonInclude(Include.NON_NULL)` annotation in all response DTOs.

Remove NON_NULL in all response DTOs

---

mico-core/src/main/java/io/github/ust/mico/core/dto/request/MicoServiceDeploymentInfoRequestDTO.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoApplicationResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoApplicationDeploymentStatus.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java

Enum values must not be in uppercase. They have to be in camel casing.

Fix invalid enum values must not be in uppercase.

---

mico-core/src/main/java/io/github/ust/mico/core/exception/KubernetesResourceException.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java

Fix error handling getting application deployment status -> If there is an error with the connection to Kubernetes, the deployment status should be `Unknown`.

Fix error handling getting application deployment status

---

mico-core/src/main/java/io/github/ust/mico/core/resource/ServiceResource.java

Update of service must not delete relationships to interfaces and dependencies.

Fix update of service must not delete relationships

---

mico-core/src/main/java/io/github/ust/mico/core/broker/BackgroundJobBroker.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceBackgroundJob.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java

During an undeployment of a MICO service an existing job will be deleted and cancelled.

Add deletion of job during undeployment of MICO service

---

mico-core/src/main/java/io/github/ust/mico/core/service/MicoStatusService.java

ArithmeticException occur if the sum of running pods are 0.

Fix aggregating cpu load and memory usage if no pod is running on node

---

mico-core/src/main/java/io/github/ust/mico/core/broker/MicoApplicationBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java

Endpoint must not throw an exception if application is undeployed

Fix get application status

---

mico-core/src/main/java/io/github/ust/mico/core/broker/BackgroundJobBroker.java
mico-core/src/main/java/io/github/ust/mico/core/broker/MicoServiceBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/BackgroundJobResource.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java

Add check if application job exists while calculating deployment status.

Fix check if application job exists

---

.github/PULL_REQUEST_TEMPLATE.md

---
Update of the pull request template
Closes #635

Update PR templete

---

mico-admin/package-lock.json
mico-admin/package.json

Update javascript dependencies to use new grapheditor release.
–

Update javascript dependencies

---

install/kubernetes/knative-build.yaml

Upgrade Knative Build to v0.7

---

pom.xml

Bump Spring Boot to version 2.1.6. Before: 2.1.3

Bump Spring Boot to version 2.1.6

---

mico-admin/src/app/forms/mico-form-boolean/mico-form-boolean.component.html
mico-admin/src/app/forms/mico-form-boolean/mico-form-boolean.component.ts

Change boolean component to update the value
closes #756

Fix frontend not sending boolean values

---

mico-core/src/main/resources/application-dev.properties
mico-core/src/main/resources/application-local.properties
mico-core/src/main/resources/application-prod.properties
mico-core/src/test/java/io/github/ust/mico/core/KubernetesDeploymentInfoRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/KubernetesNameNormalizerTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoApplicationRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoEnvironmentVariableRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoInterfaceConnectionRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoKubernetesClientTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoLabelRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoServiceDeploymentInfoRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoServiceInterfaceRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoServiceRepositoryTests.java
mico-core/src/test/java/io/github/ust/mico/core/OpenFaasFunctionsResourceTests.java

Improve test configuration:
- Fix unit tests to always use embedded Neo4j database
- Remove not used configuration properties
- Add missing configuration properties to dev profile
Documentation [Testing](https://mico-docs.readthedocs.io/en/latest/debugging-testing/testing.html) updated accordingly.

Improve test configuration

---

mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceDeploymentInfo.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoTopicRole.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoStatusService.java
mico-core/src/test/java/io/github/ust/mico/core/KafkaFaasConnectorDeploymentInfoResourceEndToEndTests.java
mico-core/src/test/java/io/github/ust/mico/core/MicoStatusServiceTest.java

Get status of application pulls kfConnector status
closes #802

Get status of application pulls kfConnector status

---

mico-core/src/main/java/io/github/ust/mico/core/broker/KafkaFaasConnectorDeploymentInfoBroker.java
mico-core/src/main/java/io/github/ust/mico/core/resource/ApplicationResource.java
mico-core/src/main/java/io/github/ust/mico/core/resource/KafkaFaasConnectorDeploymentInfoResource.java
mico-core/src/test/java/io/github/ust/mico/core/KafkaFaasConnectorDeploymentInfoResourceEndToEndTests.java

- TODO
Relates #798
Relates #750

Add GET /applications/.../kafka-faas-connector/instanceId

---

mico-core/src/main/java/io/github/ust/mico/core/broker/DeploymentBroker.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java

checks if the enabled service has the required topics set. 
closes #820

add check if kafka enabled service is deployable

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/app.module.ts
mico-admin/src/app/dialogs/graph-update-faas-function/graph-update-faas-function.component.html
mico-admin/src/app/dialogs/graph-update-faas-function/graph-update-faas-function.component.spec.ts
mico-admin/src/app/dialogs/graph-update-faas-function/graph-update-faas-function.component.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph-constants.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts

Add the kafka faas connector to the application grapheditor.

Kafka FaaS Connector in grapheditor

---

mico-admin/src/app/api/api.service.ts
mico-admin/src/app/dialogs/graph-add-kafka-topic/graph-add-kafka-topic.component.html
mico-admin/src/app/dialogs/graph-add-kafka-topic/graph-add-kafka-topic.component.ts
mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts

Add autocompletion for existing/known topics in the ui.

Autocompletion for topics in the ui

---

mico-admin/src/app/graphs/app-dependency-graph/app-dependency-graph.component.ts

Topic would only be set as input topic.
Also fix beeing unable to create topic links from a service.

Fix dragging link between kf connector and existing topic

---

mico-core/src/main/java/io/github/ust/mico/core/broker/BackgroundJobBroker.java
mico-core/src/main/java/io/github/ust/mico/core/broker/DeploymentBroker.java
mico-core/src/main/java/io/github/ust/mico/core/dto/response/MicoServiceBackgroundJobResponseDTO.java
mico-core/src/main/java/io/github/ust/mico/core/model/MicoServiceBackgroundJob.java
mico-core/src/main/java/io/github/ust/mico/core/persistence/MicoBackgroundJobRepository.java
mico-core/src/main/java/io/github/ust/mico/core/resource/BackgroundJobResource.java
mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java
mico-core/src/test/java/io/github/ust/mico/core/BackgroundJobResourceTest.java
mico-core/src/test/java/io/github/ust/mico/core/DeploymentResourceTests.java

Adds instance id to background job resource.
Add new endpoint for deleting all jobs in database:
`DELETE /jobs`
Closes #702
Closes #843

Add instanceId to job resource

---

mico-core/src/main/java/io/github/ust/mico/core/broker/BackgroundJobBroker.java

Fix job list only including own instances.

Fix job list only including own instances

---

mico-core/src/main/java/io/github/ust/mico/core/service/MicoKubernetesClient.java

Return ip in logs
